library("readxl")

Game1 <- read_excel("ForestCity_05_28.xlsx")
Game2 <- read_excel("ForestCity_06_06.xlsx")
Game3 <- read_excel("ForestCity_06_12.xlsx")
Game4 <- read_excel("ForestCity_06_15.xlsx")
Game5 <- read_excel("ForestCity_06_24_1.xlsx")
Game6 <- read_excel("ForestCity_06_24_2.xlsx")
Game7 <- read_excel("ForestCitySplitSquad_06_04.xlsx")
Game8 <- read_excel("ForestCitySplitSquad_06_25.xlsx")
Game9 <- read_excel("ForestCitySplitSquad_06_26.xlsx")
Game10 <- read_excel("Macon_06_26.xlsx")
Game11 <- read_excel("Lexington_06_17.xlsx")
Game12 <- read_excel("Savannah_06_09.xlsx")
Game13 <- read_excel("Savannah_06_10.xlsx")
Game14 <- read_excel("Savannah_06_19.xlsx")
Game15 <- read_excel("ForestCity_07_01.xlsx")
Game16<- read_excel("ForestCity_07_03.xlsx")
Game17 <- read_excel("ForestCity_07_09.xlsx")
Game18 <- read_excel("ForestCity_07_10.xlsx")
Game19 <- read_excel("ForestCity_07_15.xlsx")
Game20 <- read_excel("Lexington_07_04.xlsx")
Game21 <- read_excel("Lexington_07_08.xlsx")
Game22 <- read_excel("Lexington_06_28.xlsx")
Game23 <- read_excel("Macon_06_29.xlsx")
Game24 <- read_excel("Macon_07_11.xlsx")

PitcherSpec1 <- Game1[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]

PitcherSpec2 <- Game2[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
PitcherSpec3 <- Game3[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
PitcherSpec4 <- Game4[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
PitcherSpec5 <- Game5[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
PitcherSpec6 <- Game6[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
PitcherSpec7 <- Game7[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
PitcherSpec8 <- Game8[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
PitcherSpec9 <- Game9[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
PitcherSpec10 <- Game10[c("Date", 
                          "Pitcher",
                          "Batter",
                          "TaggedPitchType", 
                          "RelSpeed", 
                          "SpinRate" , 
                          "PitcherTeam", 
                          "Balls", 
                          "Strikes", 
                          "PitchCall",  
                          "PlayResult", 
                          "RelHeight", 
                          "RelSide", 
                          "PlateLocHeight", 
                          "PlateLocSide", 
                          "ExitSpeed",
                          "BatterSide",
                          "KorBB",
                          "Angle",
                          "Direction",
                          "Bearing",
                          "Distance")]
PitcherSpec11 <- Game11[c("Date", 
                          "Pitcher",
                          "Batter",
                          "TaggedPitchType", 
                          "RelSpeed", 
                          "SpinRate" , 
                          "PitcherTeam", 
                          "Balls", 
                          "Strikes", 
                          "PitchCall",  
                          "PlayResult", 
                          "RelHeight", 
                          "RelSide", 
                          "PlateLocHeight", 
                          "PlateLocSide", 
                          "ExitSpeed",
                          "BatterSide",
                          "KorBB",
                          "Angle",
                          "Direction",
                          "Bearing",
                          "Distance")]
PitcherSpec12 <- Game12[c("Date", 
                          "Pitcher",
                          "Batter",
                          "TaggedPitchType", 
                          "RelSpeed", 
                          "SpinRate" , 
                          "PitcherTeam", 
                          "Balls", 
                          "Strikes", 
                          "PitchCall",  
                          "PlayResult", 
                          "RelHeight", 
                          "RelSide", 
                          "PlateLocHeight", 
                          "PlateLocSide", 
                          "ExitSpeed",
                          "BatterSide",
                          "KorBB",
                          "Angle",
                          "Direction",
                          "Bearing",
                          "Distance")]
PitcherSpec13 <- Game13[c("Date", 
                          "Pitcher",
                          "Batter",
                          "TaggedPitchType", 
                          "RelSpeed", 
                          "SpinRate" , 
                          "PitcherTeam", 
                          "Balls", 
                          "Strikes", 
                          "PitchCall",  
                          "PlayResult", 
                          "RelHeight", 
                          "RelSide", 
                          "PlateLocHeight", 
                          "PlateLocSide", 
                          "ExitSpeed",
                          "BatterSide",
                          "KorBB",
                          "Angle",
                          "Direction",
                          "Bearing",
                          "Distance")]
PitcherSpec14 <- Game14[c("Date", 
                          "Pitcher",
                          "Batter",
                          "TaggedPitchType", 
                          "RelSpeed", 
                          "SpinRate" , 
                          "PitcherTeam", 
                          "Balls", 
                          "Strikes", 
                          "PitchCall",  
                          "PlayResult", 
                          "RelHeight", 
                          "RelSide", 
                          "PlateLocHeight", 
                          "PlateLocSide", 
                          "ExitSpeed",
                          "BatterSide",
                          "KorBB",
                          "Angle",
                          "Direction",
                          "Bearing",
                          "Distance")]


fifteen <- Game15[c("Date", 
                    "Pitcher",
                    "Batter",
                    "TaggedPitchType", 
                    "RelSpeed", 
                    "SpinRate" , 
                    "PitcherTeam", 
                    "Balls", 
                    "Strikes", 
                    "PitchCall",  
                    "PlayResult", 
                    "RelHeight", 
                    "RelSide", 
                    "PlateLocHeight", 
                    "PlateLocSide", 
                    "ExitSpeed",
                    "BatterSide",
                    "KorBB",
                    "Angle",
                    "Direction",
                    "Bearing",
                    "Distance")]
sixteen <- Game16[c("Date", 
                    "Pitcher",
                    "Batter",
                    "TaggedPitchType", 
                    "RelSpeed", 
                    "SpinRate" , 
                    "PitcherTeam", 
                    "Balls", 
                    "Strikes", 
                    "PitchCall",  
                    "PlayResult", 
                    "RelHeight", 
                    "RelSide", 
                    "PlateLocHeight", 
                    "PlateLocSide", 
                    "ExitSpeed",
                    "BatterSide",
                    "KorBB",
                    "Angle",
                    "Direction",
                    "Bearing",
                    "Distance")]
seventeen <- Game17[c("Date", 
                      "Pitcher",
                      "Batter",
                      "TaggedPitchType", 
                      "RelSpeed", 
                      "SpinRate" , 
                      "PitcherTeam", 
                      "Balls", 
                      "Strikes", 
                      "PitchCall",  
                      "PlayResult", 
                      "RelHeight", 
                      "RelSide", 
                      "PlateLocHeight", 
                      "PlateLocSide", 
                      "ExitSpeed",
                      "BatterSide",
                      "KorBB",
                      "Angle",
                      "Direction",
                      "Bearing",
                      "Distance")]
eighteen <- Game18[c("Date", 
                     "Pitcher",
                     "Batter",
                     "TaggedPitchType", 
                     "RelSpeed", 
                     "SpinRate" , 
                     "PitcherTeam", 
                     "Balls", 
                     "Strikes", 
                     "PitchCall",  
                     "PlayResult", 
                     "RelHeight", 
                     "RelSide", 
                     "PlateLocHeight", 
                     "PlateLocSide", 
                     "ExitSpeed",
                     "BatterSide",
                     "KorBB",
                     "Angle",
                     "Direction",
                     "Bearing",
                     "Distance")]
nineteen <- Game19[c("Date", 
                     "Pitcher",
                     "Batter",
                     "TaggedPitchType", 
                     "RelSpeed", 
                     "SpinRate" , 
                     "PitcherTeam", 
                     "Balls", 
                     "Strikes", 
                     "PitchCall",  
                     "PlayResult", 
                     "RelHeight", 
                     "RelSide", 
                     "PlateLocHeight", 
                     "PlateLocSide", 
                     "ExitSpeed",
                     "BatterSide",
                     "KorBB",
                     "Angle",
                     "Direction",
                     "Bearing",
                     "Distance")]
twenty <- Game20[c("Date", 
                   "Pitcher",
                   "Batter",
                   "TaggedPitchType", 
                   "RelSpeed", 
                   "SpinRate" , 
                   "PitcherTeam", 
                   "Balls", 
                   "Strikes", 
                   "PitchCall",  
                   "PlayResult", 
                   "RelHeight", 
                   "RelSide", 
                   "PlateLocHeight", 
                   "PlateLocSide", 
                   "ExitSpeed",
                   "BatterSide",
                   "KorBB",
                   "Angle",
                   "Direction",
                   "Bearing",
                   "Distance")]
twentyone <- Game21[c("Date", 
                      "Pitcher",
                      "Batter",
                      "TaggedPitchType", 
                      "RelSpeed", 
                      "SpinRate" , 
                      "PitcherTeam", 
                      "Balls", 
                      "Strikes", 
                      "PitchCall",  
                      "PlayResult", 
                      "RelHeight", 
                      "RelSide", 
                      "PlateLocHeight", 
                      "PlateLocSide", 
                      "ExitSpeed",
                      "BatterSide",
                      "KorBB",
                      "Angle",
                      "Direction",
                      "Bearing",
                      "Distance")]
twentytwo <- Game22[c("Date", 
                      "Pitcher",
                      "Batter",
                      "TaggedPitchType", 
                      "RelSpeed", 
                      "SpinRate" , 
                      "PitcherTeam", 
                      "Balls", 
                      "Strikes", 
                      "PitchCall",  
                      "PlayResult", 
                      "RelHeight", 
                      "RelSide", 
                      "PlateLocHeight", 
                      "PlateLocSide", 
                      "ExitSpeed",
                      "BatterSide",
                      "KorBB",
                      "Angle",
                      "Direction",
                      "Bearing",
                      "Distance")]
twentythree <- Game23[c("Date", 
                        "Pitcher",
                        "Batter",
                        "TaggedPitchType", 
                        "RelSpeed", 
                        "SpinRate" , 
                        "PitcherTeam", 
                        "Balls", 
                        "Strikes", 
                        "PitchCall",  
                        "PlayResult", 
                        "RelHeight", 
                        "RelSide", 
                        "PlateLocHeight", 
                        "PlateLocSide", 
                        "ExitSpeed",
                        "BatterSide",
                        "KorBB",
                        "Angle",
                        "Direction",
                        "Bearing",
                        "Distance")]
twentyfour <- Game24[c("Date", 
                       "Pitcher",
                       "Batter",
                       "TaggedPitchType", 
                       "RelSpeed", 
                       "SpinRate" , 
                       "PitcherTeam", 
                       "Balls", 
                       "Strikes", 
                       "PitchCall",  
                       "PlayResult", 
                       "RelHeight", 
                       "RelSide", 
                       "PlateLocHeight", 
                       "PlateLocSide", 
                       "ExitSpeed",
                       "BatterSide",
                       "KorBB",
                       "Angle",
                       "Direction",
                       "Bearing",
                       "Distance")]




Comb1 <- rbind(PitcherSpec1, PitcherSpec2) 
Comb2 <- rbind(PitcherSpec3, PitcherSpec4) 
Comb3 <- rbind(PitcherSpec5, PitcherSpec6) 
Comb4 <- rbind(PitcherSpec9, PitcherSpec7) 
Comb5 <- rbind(PitcherSpec8, PitcherSpec10) 
Comb6 <- rbind(PitcherSpec11, PitcherSpec12) 

PitcherCombb1 <- rbind(PitcherSpec13, Comb1) 
PitcherCombb2 <- rbind(PitcherSpec14, Comb6) 



PitcherCombs2 <- rbind(Comb3, Comb4) 
PitcherCombs3 <- rbind(Comb5, PitcherCombb2) 


Combbs1 <- rbind(Comb2, PitcherCombs3) 
Combbs2 <- rbind(PitcherCombb1, PitcherCombs2) 



PitcherSpecs <- rbind(Combbs1, Combbs2)

takeone <- rbind(PitcherSpecs, fifteen)

taketwo <- rbind(takeone, sixteen)
takethree <- rbind(taketwo, seventeen)
takefour <- rbind(takethree, eighteen)
takefive <- rbind(takefour, nineteen)
takesix <- rbind(takefive, twenty)
takeseven <- rbind(takesix, twentyone)
takeeight <- rbind(takeseven, twentytwo)
takenine <- rbind(takeeight, twentythree)
taketen <- rbind(takenine, twentyfour)

BurgSpec <- subset(taketen, PitcherTeam=="SPA_B")

BurgSpecH <- subset(taketen, PitcherTeam !="SPA_B")

